accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('<int:user_pk>/', views.people, name='people'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('password/', views.password, name='password'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name="signup"),      
]

movies/urls.py
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('highest/', views.highest, name='highest'),
    path('popularity/', views.popularity, name='popularity'),
    path('search/', views.search, name='search'),
    path('main/', views.main, name='main'),
    path('wishes/', views.wishes, name='wishes'),
    path('evaluate/', views.evaluate, name='evaluate'),
    # path('<int:movie_pk>/scores/<int:score_pk>/show_spoiler', views.show_spoiler, name='show_spoiler'),
    # path('<int:movie_pk>/hate/', views.hate, name='hate'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/scores/<int:score_pk>/update/', views.score_update, name='score_update'),
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.score_delete, name='score_delete'),
    path('<int:movie_pk>/scores/new/', views.score_create, name='score_create'),
    # path('<int:movie_pk>/delete/', views.delete, name='delete'),    
    # path('<int:movie_pk>/update/', views.update, name='update'),    
    path('<int:movie_pk>/', views.detail, name='detail'),    
    # path('create', views.create, name='create'),    
    path('list/', views.list, name='list'),    
    path('', views.index, name='index'),    
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),    
    path('<int:post_pk>/discuss/create/', views.comment_create, name='comment_create'),    
    path('<int:post_pk>/delete/', views.delete, name='delete'),    
    path('<int:post_pk>/update/', views.update, name='update'),    
    path('<int:post_pk>/discuss/', views.detail, name='detail'),    
    path('<int:movie_pk>/create/', views.create, name='create'),    
    path('<int:movie_pk>/', views.index, name='index'),
    # path('', view.list, name='list'),
]

watchb/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from movies import views as movies_view

urlpatterns = [
    path('', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=255)
    original_title = models.CharField(max_length=255)
    vote_average = models.FloatField()
    popularity = models.FloatField()
    poster_url = models.TextField(blank=True)
    backdrop_url = models.TextField(blank=True)
    overview = models.TextField()
    release_date = models.DateField()
    vote_count = models.IntegerField()
    runtime = models.IntegerField(blank=True, null=True)
    video = models.CharField(max_length=255, blank=True)
    movie_genre = models.ManyToManyField(Genre, related_name='genre_movie')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movie', blank=True)
    hate_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='hate_movie', blank=True)
    saw_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_saw', blank=True)
    
class Director(models.Model):
    director_movie = models.ManyToManyField(Movie, related_name='movie_director')
    name = models.CharField(max_length=255)
    profile_path = models.TextField(blank=True)
    
    def __str__(self):
        return self.name
    
class Actor(models.Model):
    name = models.CharField(max_length=255)
    profile_path = models.TextField(blank=True)
    credit_id = models.CharField(max_length=255)
    cast_id = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Cast(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    character = models.CharField(max_length=255)

class Score(models.Model):
    review = models.CharField(max_length=255, blank=True)
    score = models.FloatField()
    spoiler = models.BooleanField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

movies/forms.py
from django import forms
from .models import Movie, Score

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'vote_average', 'popularity',]
        
class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['review', 'score', 'spoiler',]

movies/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponseBadRequest
from django.db.models import Q
from .models import Movie, Score, Genre
from accounts.models import User
from .forms import MovieForm, ScoreForm
from django.core.paginator import Paginator
import json

# Create your views here.
# 홈
@login_required
def index(request):
    user = request.user
    movie = Movie.objects.all()
    movie = movie.exclude(saw_user=user)
    popular_movies = movie.order_by('-popularity')[0:60]
    highest_movies = movie.order_by('-vote_average')[0:min(60, movie.count())]
    user_movie =  user.like_movie.all().order_by('?')[0:min(60, movie.count())]
    play_movie_1 = movie.order_by('-popularity')[0]
    random_movie = movie.order_by('?')[0]
    followings = User.objects.filter(followers=user)
    if followings:
        following = followings.order_by('?')[0]
        following_saw = Movie.objects.filter(saw_user=following)
        following_saw = following_saw.exclude(Q(saw_user=user) | Q(vote_average__lt=7))
        following_saw = following_saw.order_by('-vote_average')[0:min(60, Movie.objects.all().count())]
    else:
        following_saw = Movie.objects.none()
    genres_count = []
    genres = Genre.objects.all()
    max_count = 0
    for genre in genres:
        count = genre.genre_movie.count()
        if count >= max_count:
            max_count = count
            max_genre = genre
    favorite_genre = max_genre.genre_movie.all()
    favorite_genre = favorite_genre.exclude(saw_user=user)[:min(60, favorite_genre.all().count())]
    # user_saw = Movie.objects.filter(saw_user=user)
    # genres = Genre.objects.filter(genre_movie=user_saw)
    context = {
        'popular_movies': popular_movies,
        'highest_movies': highest_movies,
        'user': user,
        'user_movie': user_movie,
        'random_movie': random_movie,
        'following_saw': following_saw,
        'favorite_genre': favorite_genre,
    }
    return render(request, 'movies/index.html', context)



# 영화 리스트    
@login_required
def list(request):
    # movies = get_list_or_404(Movie.objects.order_by('-popularity'))[0:10]
    popular_movies = Movie.objects.all().order_by('-popularity')[0:60]
    highest_movies = Movie.objects.all().order_by('-vote_average')[0:60]
    context = {
        'popular_movies': popular_movies,
        'highest_movies': highest_movies,
    }
    return render(request, 'movies/list.html', context)
    
def main(request):
    movies = get_list_or_404(Movie.objects.order_by('-popularity'))[0:10]
    context = {
        'movies': movies,
    }
    return render(request, 'movies/test.html', context)
    
# 영화 생성
# @login_required
# def create(request):
#     # if request.user.is_superuser:
            
#     if request.method == 'POST':
#         movie_form = MovieForm(request.POST)
#         if movie_form.is_valid():
#             movie = movie_form.save(commit=False)
#             movie.user = request.user
#             movie.save()
#             return redirect('movies:list')
#     else:
#         movie_form = MovieForm()
#     context = {
#         'movie_form': movie_form,
#     }
#     return render(request, 'movies/create.html', context)
    
    # else:
    #     return render()

# 영화정보 수정    
# @login_required
# def update(request, movie_pk):
#     movie = get_object_or_404(Movie, pk=movie_pk)
    
#     # if movie.user != request.user:
#     #     return redirect('movies:list')
    
#     if request.method == 'POST':
#         movie_form = MovieForm(request.POST, instance=movie)
#         if movie_form.is_valid():
#             movie = movie_form.save()
#             return redirect('movies:list')
            
#     else:
#         movie_form = MovieForm(instance=movie)
#     context = {
#         'movie_form': movie_form,
#         'movie': movie,
#     }
#     return render(request, 'movies/update.html', context)

# 영화 상세
@login_required
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    actors = movie.cast_set.all()[0:5]
    score_form = ScoreForm()
    context = {
        'movie': movie,
        'score_form': score_form,
        'actors': actors,
    }
    return render(request, 'movies/detail.html', context)

# 영화 삭제
# def delete(request, movie_pk):
#     movie = get_object_or_404(Movie, pk=movie_pk)
    
#     # if movie.user != request.user:
#     #     return redirect('movies:list')
        
#     if request.method == 'POST':
#         movie.delete()
#     return redirect('movies:list')
    
# 평 생성
@login_required
@require_POST
def score_create(request, movie_pk):
    form = ScoreForm(request.POST)
    if form.is_valid():
        score = form.save(commit=False)
        score.user = request.user
        score.movie_id = movie_pk
        score.save()
        movie = get_object_or_404(Movie, pk=movie_pk)
        movie.saw_user.add(request.user)
        total = movie.vote_count * movie.vote_average
        total += score.score
        movie.vote_count += 1
        movie.vote_average = round(total / movie.vote_count, 2)
    # 점수 변경 추가하기
        return redirect('movies:detail', movie_pk)
    else:
        return redirect('movies:list')

# 평 삭제
@login_required
def score_delete(request, movie_pk, score_pk):
    score = get_object_or_404(Score, pk=score_pk)
    num = score.score
    score.delete()
    movie = get_object_or_404(Movie, pk=movie_pk)
    total = movie.vote_average * movie.vote_count
    total -= num
    movie.vote_count -= 1
    movie.vote_average = round(total / movie.vote_count, 2)
    movie.saw_user.remove(request.user)
    # 점수 변경 추가하기
    return redirect('movies:detail', movie_pk)

@login_required
def score_update(request, movie_pk, score_pk):
    score = get_object_or_404(Score, pk=score_pk)
    old = score.score
    
    # if movie.user != request.user:
    #     return redirect('movies:detail')
    
    if request.method == 'POST':
        score_form = ScoreForm(request.POST, instance=score)
        if score_form.is_valid():
            scores = score_form.save()
            new = scores.score
            movie = get_object_or_404(Movie, pk=movie_pk)
            total = movie.vote_count * movie.vote_average
            total += (new - old)
            movie.vote_average = round(total / movie.vote_count, 2)
            return redirect('movies:detail', movie_pk)
            
    else:
        score_form = ScoreForm(instance=score)
    context = {
        'score_form': score_form,
        # 'score': score,
        # 'movie_pk': movie_pk,
    }
    return render(request, 'movies/score_update.html', context)


    
# 영화 보고싶어요
@login_required
def like(request, movie_pk):
    if request.is_ajax():
        movie = get_object_or_404(Movie, pk=movie_pk)
        if request.user in movie.like_users.all():
            movie.like_users.remove(request.user)
            liked = False
            movie.popularity -= 1
        else:
            movie.like_users.add(request.user)
            liked = True
            movie.popularity += 1
        return JsonResponse({'liked': liked})
    else:
        return HttpResponseBadRequest()

# 영화 관심없어요
# @login_required
# def hate(request, movie_pk):
#     if request.is_ajax():
#         movie = get_object_or_404(Movie, pk=movie_pk)
#         if request.user in movie.hate_users.all():
#             movie.hate_users.remove(request.user)
#             hated = False
#             liked = False
#         else:
#             movie.hate_users.add(request.user)
#             if request.user in movie.like_users.all():
#                 liked = True
#             hated = True
#         context = {
#             'liked': liked,
#             'hated': hated
#         }
#         return JsonResponse(context)
#     else:
#         return HttpResponseBadRequest()
    
    
# 보고싶어요 / 관심없어요
@login_required
def wishes(request):
    user = request.user
    movie = Movie.objects.all()
    movie = movie.exclude(saw_user=user)
    movies = movie.order_by('-popularity')
    if not movies:
        movies = Movie.objects.none()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/wishes.html', context)
    
# 평가하기
@login_required
def evaluate(request):
    movies = get_list_or_404(Movie.objects.all().order_by('-popularity'))
    paginator = Paginator(movies, 6)
    page = request.GET.get('page')
    movie_list = paginator.get_page(page)
    context = {
        'movies': movies,
        'movie_list': movie_list,
    }
    return render(request, 'movies/evaluate.html', context)
    
    
@login_required
def search(request):
    if request.is_ajax():
        # data = json.loads(request.body.decode('utf-8'))
        # print(data)
        # return redirect('movies:list')
        # statuss = Movie.objects.filter(title__contains='wild')
        # context = {
        #     'statuss': statuss
        # }
        # return render(request, 'movies/index.html', context)
        title = json.loads(request.body.decode('utf-8'))
        title = request.POST.get('title', None)
        statuss = Movie.objects.filter(title__contains=title)
        context = {
            'statuss': statuss
        }
        return render(request, 'movies/index.html', context)
    else:
        return HttpResponseBadRequest()
        
# 추천 페이지
@login_required
def popularity(request):
    movie = Movie.objects.all()
    popular_movies = movie.order_by('-popularity')[0:60]
    context = {
        'popular_movies': popular_movies,
    }
    return render(request, 'movies/popularity_list.html', context)
    
def highest(request):
    movie = Movie.objects.all()
    highest_movies = movie.order_by('-vote_average')[0:60]
    context = {
        'highest_movies': highest_movies,
    }
    return render(request, 'movies/highest_list.html', context)

movies/templates/movies/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top">
        <a class="navbar-brand text-white my-auto ml-5" href="{% url 'movies:index' %}">
            <p class='my-auto' style="font-size:30px;"><img src="{% static 'movies/img/logo/logo3.JPG' %}" alt=""> 영복동</p>
        </a>
        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id='navbarNavDropdown'>
            <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:index' %}">홈</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:evaluate' %}">평가하기</a>
                    </li>
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">장르</a>
                        <ul class="dropdown-menu multi-column columns-3">
                        <div class="row">
    			            <div class="col-lg-4">
    				            <ul class="multi-column-dropdown">
    					            <a class="dropdown-item" href="#">액션</a>
    					            <a class="dropdown-item" href="#">모험</a>
    					            <a class="dropdown-item" href="#">애니메이션</a>
    					            <a class="dropdown-item" href="#">코미디</a>
    					            <a class="dropdown-item" href="#">범죄</a>
    					            <a class="dropdown-item" href="#">다큐멘터리</a>
    					            <a class="dropdown-item" href="#">드라마</a>
    				            </ul>
    			            </div>
    			            <div class="col-lg-4">
    				            <ul class="multi-column-dropdown">
    					            <a class="dropdown-item" href="#">가족</a>
    					            <a class="dropdown-item" href="#">판타지</a>
    					            <a class="dropdown-item" href="#">역사</a>
    					            <a class="dropdown-item" href="#">공포</a>
    					            <a class="dropdown-item" href="#">음악</a>
    					            <a class="dropdown-item" href="#">미스터리</a>
    				            </ul>
    			            </div>
    			            <div class="col-lg-4">
    				            <ul class="multi-column-dropdown">
    					            <a class="dropdown-item" href="#">로맨스</a>
    					            <a class="dropdown-item" href="#">SF</a>
    					            <a class="dropdown-item" href="#">TV 영화</a>
    					            <a class="dropdown-item" href="#">스릴러</a>
    					            <a class="dropdown-item" href="#">전쟁</a>
    					            <a class="dropdown-item" href="#">서부</a>
    				            </ul>
    			            </div>
    		            </div>
    		            </ul>
                    </li>
                </ul>
                <ul class="navbar-nav mr-5 ml-auto">
                    <li class="nav-item d-flex align-items-center">
                        <form method="POST">
                        {% csrf_token %}
                        <input id='searchMovie' class="form-control" type="search" placeholder="영화 검색" aria-label="Search">
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:wishes' %}">보고싶어요</a>
                    </li>
                <li class="nav-item dropdown justify-content-end">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
                        <a class="dropdown-item" href="{% url 'accounts:people' user.pk %}">프로필</a>
                        <!--<a class="dropdown-item" href="{% url 'accounts:login' %}">로그인</a>-->
                        
                    </div>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <span class="badge badge-pill badge-light"><a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a></span>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script>
        $('#searchMovie').keyup(function() {
            $('#searchMovie').each(function() {
                var searching = $('#searchMovie').val()
                axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
                axios.defaults.xsrfCookieName = 'csrftoken'
                axios.defaults.xsrfHeaderName = 'X-CSRFToken'
                axios.post('/movies/search/', { title: searching, })
                    .then(response => {
                        console.log(response, JSON.stringify(response, null, 2))
                    })
                    .catch(error => console.log(error, searching))
            });
         });
    </script>

movies/templates/movies/_user_movie.html
{% load static %}
{% load movie_templates %}
<link rel="stylesheet" type="text/css" href="{% static 'movies/carousel.css' %}">

<div class="text-center my-3">
    <div class="d-flex justify-content-between">
        <span class='ml-5 text-white' style='font-size:1.4vw;'>당신이 보고 싶어했던 영화</span>
        <span class='mr-5 text-white' style='font-size:1.4vw;'>모두 보기<i class="fas fa-angle-right"></i></span>
    </div>
    <div id="wantCarousel" class="carousel slide w-100" data-ride="carousel" data-interval="false">
        <div class="carousel-inner w-100" role="listbox">
            {% for um in user_movie|slice:":12" %}
                {% if forloop.counter == 1 %}
                    <div class="carousel-item row no-gutters active hover_container">
                {% endif %}
                        <div class="col-2 float-left" data-toggle="modal" data-target="#movieModal">
                        <p class="text-white" style="font-size: 20px; position: absolute; bottom: 0px; left: 16px;">{{ um.title }}</p>
                            <img class="img-fluid hover_image" src="{{ um.backdrop_url }}">
                        </div>
                {% if forloop.counter == 6 %}
                    </div>
                    <div class="carousel-item row no-gutters">
                {% endif %}
            {% endfor %}
            </div>
        </div>
        <a class="carousel-control-prev" href="#wantCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon mr-auto" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#wantCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon ml-auto" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id='name'></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block head %}
    <style>
        /*p {*/
        /*    color: white;*/
        /*}*/
        .container {
            color: white;
            /*background-image: url("{{ movie.poster_url }}");*/
            
        }
        
        hr{ 
            height: 1px;
            color: white;
            background-color: white;
            border: none;
        }
    </style>
{% endblock %}

{% block content %}
    <br>
    <div class="container">
        <h1>{{ movie.title }}</h1>
        <p>{{ movie.original_title }}</p>
        <!--<div class="input-group btn-group btn-group-sm">-->
        <!--    <div class="input-group-prepend">-->
        <!--        <div class="input-group-text" id="btnGroupAddon">평점</div>-->
        <!--    </div>-->
        <!--    <input type="text" class="form-control" aria-label="{{ movie.vote_average }}">-->
        <!--</div>-->
        <p><b>평점 :</b> {{ movie.vote_average }} | {{ movie.runtime }}분</p>
        <h3 class="text-secondary">줄거리</h3>
        <p class="text-secondary">{{ movie.overview }}</p>
        <p class="text-dark"><b>감독 :</b>
            {% for director in movie.movie_director.all %}
                {{ director }}
            {% endfor %}
        </p>
        <p class="text-dark"><b>출연 :</b>
            {% for actor in actors %}
                {{ actor.actor }}, 
            {% endfor %}
        </p>
        <p class="text-dark"><b>인기도 :</b> {{ movie.popularity }}</p>
        <p class="text-dark"><b>장르 :</b>
            {% for genre in movie.movie_genre.all %}
                {{ genre }}
            {% endfor %}
        </p>
        
        {% if movie.video %}
            <button type="button" class="btn btn-danger btn-xs" onclick="window.open('{{ movie.video }}', '{{ movie.title }}예고편 영상'); return false"><i class="far fa-play-circle"></i> 재생</button>
        {% else %}
            <button type="button" class="btn btn-danger btn-xs" disabled>예고편을 지원하지 않는 영화 입니다.</button>
        {% endif %}
        
        
        <!--<button type="button" class="btn btn-danger btn-xs"><i class="far fa-play-circle"></i> 예고편</button>-->
        <i class="{% if user in movie.like_users.all %}fas{% else %}far{% endif %} fa-heart fa-lg text-danger like-button" data-id="{{ movie.pk }}" style="color:crimson"></i>
        
       
        <!--<p>{{ movie.cast_set.all }}</p>-->
        <!--<p>{{ movie.cast_set.all.first }}</p>-->
        <!--<p>{{ movie.cast_set.all.first.actor }}</p>-->
        
        <!--{# for actors in movie.cast_set.all #}-->
        <!--    {# actors.actor #},-->
        <!--{# endfor #}-->
        
   
        
        
        <!--<hr>-->
        <!--<form action="{# url 'movies:delete' movie.pk #}" method="POST">-->
        <!--    {% csrf_token %}-->
        <!--    <input type="submit" value="삭제"/>-->
        <!--</form>-->
        <!--<a href="{# url 'movies:update' movie.pk #}">수정</a>-->
        <hr>
        <h3>작성된 평</h3>
        {% for score in movie.score_set.all %}
            <strong>{{ score.user }}</strong>: {{ score.score }}점 <span class="text-muted">{{ score.created|timesince }} 전</span><br>
            
            <!--{{ score.review }}-->
            {% if score.user == request.user %}
            <form action="{% url 'movies:score_delete' movie.pk score.pk %}" method="POST" style="display:inline;">
                {% csrf_token %}
                {% if score.spoiler %}
                    <!--<p>이 코멘트에는 스포일러가 있어요. <a href="" class="text-danger font-weight-bold">보기</a></p>-->
                    <input class="spoilerbutton text-danger font-weight-bold" type="button" value="스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요." onclick="this.value=this.value=='스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요.'?'{{ score.review }}':'스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요.';">
                    <div class="spoiler"><div>
                    <!--<p>test  </p>-->
                    <!--<p>  </p>-->
                    </div></div>
                    
                    <!--<button type="button" class="btn btn-outline-light">{{ score.review }}</button>-->
                    <!--<p>스포일러가 포함된 댓글입니다. 댓글을 보려면 마우스를 올려주세요.</p>-->
                {% else %}
                    <p>{{ score.review }}</p>
                {% endif %}
                <input type="submit" value="❌"/>
            </form>
            <a href="{% url 'movies:score_update' movie.pk score.pk %}">수정하기</a>
            {% endif %}
            <br>
        {% endfor %}
            
        <hr>
            <h3>리뷰/평점</h3>
            {% if user.is_authenticated %}
            <form action="{% url 'movies:score_create' movie.pk %}" method="POST">
                {% csrf_token %}
                {{ score_form }}
                <input type="submit" value="작성하기"/>
            </form>
            {% else %}
            <a href="{% url 'accounts:login' %}"><p>로그인이 필요합니다.</p></a>
            {% endif %}
    <hr>
    <a href="{% url 'posts:index' movie.pk %}" class="text-white">토론게시판</a>
    </div>
 

{% endblock %}

movies/templates/movies/like_hate(main).html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>보고싶어요 / 관심없어요 누른 영화</title>
</head>
<body>
    <p>보고싶어요</p>
    {% for movie in user.like_movie.all %}
        <li>{{ movie.title }}</li>
    {% endfor %}
    <hr>
    <p>관심없어요</p>
    {% for movie in user.hate_movie.all %}
        <li>{{ movie.title }}</li>
    {% endfor %}
    
</body>
</html>

movies/templates/movies/score_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <!--{{ form }}-->
        {{ score_form }}
       
        
        <input type="submit" value="Submit"/>
    </form>

{% endblock %}