accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('<int:user_pk>/', views.people, name='people'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('password/', views.password, name='password'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name="signup"),      
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),    
    path('<int:post_pk>/discuss/create/', views.comment_create, name='comment_create'),    
    path('<int:post_pk>/delete/', views.delete, name='delete'),    
    path('<int:post_pk>/update/', views.update, name='update'),    
    path('<int:post_pk>/discuss/', views.detail, name='detail'),    
    path('<int:movie_pk>/create/', views.create, name='create'),    
    path('<int:movie_pk>/', views.index, name='index'),
    # path('', view.list, name='list'),
]

watchb/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from movies import views as movies_view

urlpatterns = [
    path('', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=40, blank=True)
    introduction = models.TextField(blank=True)

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')
    

posts/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie
from django.contrib.auth.decorators import login_required

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    spoiler = models.BooleanField()
    
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    # def __str__(self):
    #     return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile

# 회원정보수정
class CustomUserChangeForm(UserChangeForm):
    class Meta():
        model = get_user_model()
        fields = ['first_name', 'last_name']

# 회원가입
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        
# 프로필
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import CustomUserCreationForm, CustomUserChangeForm, ProfileForm
from .models import Profile

# Create your views here.
# 회원가입
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('movies:index')
    
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

# 로그인
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)
    
# 로그아웃
@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')
    
# 
def people(request, user_pk):
    people = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        'people': people,
    }
    return render(request, 'accounts/people.html', context)
    
# 회원정보수정
@login_required
def update(request):
    if request.method == 'POST':
        # pass
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('people', request.user.username)
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
    context = {
        'user_change_form': user_change_form,
    }
    return render(request, 'accounts/update.html', context)
        

# 회원탈퇴
@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()
    return redirect('movies:index')

# 비밀번호변경
@login_required
def password(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
    context = {
        'password_change_form': password_change_form,
    }
    return render(request, 'accounts/password.html', context)
    
# 프로필 수정
@login_required
def profile_update(request):
    profile = Profile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    context = {
        'profile_form': profile_form,
    }
    return render(request, 'accounts/profile_update.html', context)
    
# Follow
@login_required
def follow(request, user_pk):
    people = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in people.followers.all():
        people.followers.remove(request.user)
    else:
        people.followers.add(request.user)
    return redirect('accounts:people', people.pk)

accounts/templates/accounts/like.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">{{ people.username }}'s Profile</h1>
<div class="jumbotron jumbotron-fluid text-center mb-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{ people.profile.nickname }}</h1>
    <p class="lead">{{ people.profile.introduction }}</p>
    <hr class="border-white my-4">
    <p class="lead">팔로잉 : {{ people.followings.count }} / 팔로워 : {{ people.followers.count }}</p>
    {% if user != people %}
        {% if user in people.followers.all %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-outline-primary">Unfollow</a>
        {% else %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-primary">Follow</a>
        {% endif %}
    {% endif %}
  </div>
</div>

<h3 class="text-center"><b>{{ people.username }}</b>님이 보고싶어요한 작품</h3>
<div class="row">
    {% for post in people.post_set.all|dictsortreversed:"pk" %}
    <div class="col-4 my-3">
        <div class="card">
            <img src="{{ post.image_set.first.file.url }}" class="card-img-top" alt="{{ post.image_set.first.file }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.content }}</h5>
                <p class="card-text">{{ post.like_users.count }}명이 좋아합니다.</p>
                <p class="card-text">{{ post.comment_set.count }}개의 댓글</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<h3 class="text-center">{{ people.username }}이 작성한 댓글</h3>
<div class="row">
    {% for comment in people.comment_set.all %}
    <div class="col-12 my-2">
        <div class="card">
            <div class="card-body">
                <blockquote class="blockquote">
                    <p class="mb-0">{{ comment.post.content }}</p>  <!-- comment.post.content == comment.post -->
                    <footer class="blockquote-footer">{{ comment.content }}</footer>    <!-- comment.content == comment -->
                </blockquote>
            </div>
        </div>
    </div>
    {% endfor %}
</div>









{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block head %}
<style>
    html,body{
    /*background-image: url('../static/accounts/img/login.jpg');*/
    background-image: url('https://images2.alphacoders.com/760/760735.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    height: 100%;
    font-family: 'Numans', sans-serif;
    background-position: center center;
    overflow: hidden;
    }
    
    .container{
    height: 100%;
    align-content: center;
    }
    
    .card{
    height: 370px;
    margin-top: auto;
    margin-bottom: auto;
    width: 400px;
    background-color: rgba(0,0,0,0.5) !important;
    }
    
    .social_icon a{
    color: black;
    width: 200px;
    height: 50px;
    text-align: center;
    line-height: 44px;
    font-size: 15px;
    }
    
    .social_icon span:hover{
    color: white;
    cursor: pointer;
    }
    
    .card-header h3{
    color: white;
    }
    
    .input-group-prepend span{
    width: 50px;
    background-color: #FFC312;
    color: black;
    border:0 !important;
    }
    
    input:focus{
    outline: 0 0 0 0  !important;
    box-shadow: 0 0 0 0 !important;
    
    }
    
    .remember{
    color: white;
    }
    
    .remember input
    {
    width: 20px;
    height: 20px;
    margin-left: 15px;
    margin-right: 5px;
    }
    
    .login_btn{
    color: black;
    background-color: #FFC312;
    width: 100px;
    }
    
    .login_btn:hover{
    color: black;
    background-color: #d39e00;
    }
    
    .links{
    color: white;
    }
    
    .links a{
    margin-left: 4px;
    }
    
    .card-footer > span {
        color: white;
        font-size: 13px;
    }
    
    #find {
        color: #9E9E9E;
        font-size: 14px;
    }
    
    #kakao {
        position: relative;
        top: 15px;
        left: 40px;
        width: 20px;
        height: 20px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header justify-content-between">
				<h3>로그인</h3>
				<a href="#" id='find'>비밀번호를 잊어버리셨나요?</a>
			</div>
			<div class="card-body">
				<form method="POST">
				    {% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username" name='username'>
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password" name='password'>
					</div>
					<div class="form-group">
						<input type="submit" value="로그인" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer text-center">
			    <span >이전에 카카오로 가입하셨나요?</span>
				<div class="d-flex justify-content-center social_icon">
				    <img src="{% static 'accounts/img/kakao.png' %}" alt="kakao" id="kakao" class='d-inline'>
                    <a href="{% provider_login_url 'kakao' method='oauth2' %}" class="badge badge-pill badge-warning">카카오로그인</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/password.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>비밀번호변경</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form password_change_form %}
        {% buttons submit="변경" reset="cancel" %}{% endbuttons %}
        
        <!--<input type="submit" value="Submit"/>-->
    </form>

</body>
</html>

accounts/templates/accounts/people.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<br>
    <h1 class="text-center text-white">{{ people.username }}'s Profile</h1>
    <div class="jumbotron jumbotron-fluid text-center mb-2">
      <div class="container">
        <h1 class="display-4">{{ people.profile.nickname }}</h1>
        <p class="lead">{{ people.profile.introduction }}</p>
        <hr class="my-4 border-white">
        <p class="lead">팔로잉 : {{ people.followings.all.count }} / 팔로워 : {{ people.followers.all.count }}</p>
        {% if user != people %}
            {% if user in people.followers.all %}
            <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-outline-primary">Unfollow</a>
            {% else %}
            <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-primary">Follow</a>
            {% endif %}
        {% endif %}
      </div>
    </div>
    {% if people == user %}
    <div class="text-center">
        <a href="{% url 'accounts:update' %}" class="badge badge-info">회원정보 수정</a>
        <a href="{% url 'accounts:profile_update' %}" class="badge badge-success">프로필 수정</a>
        <a href="{% url 'accounts:password' %}" class="badge badge-war">비밀번호 변경</a>
    </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/profile_update.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>프로필 수정</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form profile_form %}
        {% buttons submit="수정" reset="cancel" %}{% endbuttons %}
        <a href="{% url 'people' user.username %}" class="btn btn-info">Back</a>
        <!--<input type="submit" value="Submit"/>-->
    </form>

</body>
</html>

accounts/templates/accounts/signup.1.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
<style>
    html,body{
    background-image: url('https://images2.alphacoders.com/760/760735.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    height: 100%;
    font-family: 'Numans', sans-serif;
    background-position: center center;
    overflow: hidden;
    }
</style>
{% endblock %}
{% block content %}

{% endblock %}

<!DOCTYPE html>
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <title>Document</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>회원가입</h1>-->
<!--    <form action="" method="POST">-->
<!--        {% csrf_token %}-->
        <!--{{ form }}-->
<!--        {% bootstrap_form form %}-->
<!--        {% buttons submit="회원가입" reset="cancel" %}{% endbuttons %}-->
        
        <!--<input type="submit" value="Submit"/>-->
<!--    </form>-->

<!--</body>-->
<!--</html>-->

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
<style>
    html,body{
    background-image: url('https://images2.alphacoders.com/760/760735.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    height: 100%;
    font-family: 'Numans', sans-serif;
    background-position: center center;
    background-blend-mode: multiply;
    overflow: hidden;
    }
    
    .container{
    height: 100%;
    align-content: center;
    }
    
    h3 {
        font-size: 20px;
        color: white;
    }
    
    .form-group > .btn{
        width: 300px;
        height: 40px;
        text-align: center;
        font-size: 18px;
        line-height: 30px;
        background-color: #dc3545;
        border-radius: 10rem;
        color: white;

    }
    .form-group > .btn:hover {
        /*color: black;*/
        background-color: #C82333;
    }
    
    #sign {
    height: 370px;
    margin-top: auto;
    margin-bottom: auto;
    width: 300px;
    background-color: rgba(0,0,0,0) !important;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
	<div class="d-flex justify-content-center h-100">
	    <div id="sign">
    		<h3>회원가입</h3>
    		<form method="POST">
    		    {% csrf_token %}
    			<div class="input-group form-group">
    				<input type="text" class="form-control" placeholder="이름(홍길동)" name='username'>
    			</div>
    			<div class="input-group form-group">
    				<input type="password" class="form-control" placeholder="비밀번호(8자 이상)" name='password1'>
    			</div>
    			<div class="input-group form-group">
    				<input type="password" class="form-control" placeholder="비밀번호 확인" name='password2'>
    			</div>
    			<div class="form-group">
    			    <input type="submit" value="회원가입" class="btn btn-waring float-right login_btn">
    			</div>
    		</form>
	    </div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/update.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>회원정보수정</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form user_change_form %}
        {% buttons submit="수정" reset="cancel" %}{% endbuttons %}
        
        <!--<input type="submit" value="Submit"/>-->
    </form>
    <hr>
    <form action="{% url 'accounts:delete' %}" method="POST" style="display:inline;" onsubmit="return confirm('R U SURE?');">
        {% csrf_token %}
        <a href="{% url 'people' user.username %}" class="btn btn-info">Back</a>
        <button type="submit" class="btn btn-danger">회원탈퇴</button>
    </form>
</body>
</html>