accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('<int:user_pk>/', views.people, name='people'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('password/', views.password, name='password'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name="signup"),      
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('<int:post_pk>/delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),    
    path('<int:post_pk>/discuss/create/', views.comment_create, name='comment_create'),    
    path('<int:post_pk>/delete/', views.delete, name='delete'),    
    path('<int:post_pk>/update/', views.update, name='update'),    
    path('<int:post_pk>/discuss/', views.detail, name='detail'),    
    path('<int:movie_pk>/create/', views.create, name='create'),    
    path('<int:movie_pk>/', views.index, name='index'),
    # path('', view.list, name='list'),
]

watchb/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from movies import views as movies_view

urlpatterns = [
    path('', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

posts/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie
from django.contrib.auth.decorators import login_required

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    spoiler = models.BooleanField()
    
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    # def __str__(self):
    #     return self.content

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'spoiler',]
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

posts/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
# def list(request):
#     posts = get_list_or_404(Movie.objects.order_by('-popularity'))

@login_required
def index(request, movie_pk):
    # posts = get_list_or_404(Post.objects.order_by('-pk'), movie_id=movie_pk)
    posts = Post.objects.filter(movie_id=movie_pk)
    if not posts:
        posts = Post.objects.none()
    paginator = Paginator(posts, 3) # 추가
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {
        'movie_pk': movie_pk,
        'posts': posts,
        'post_list': post_list,
    }
    return render(request, 'posts/index.html', context)
    
@login_required
def create(request, movie_pk):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.movie_id = movie_pk
            post.save()
            return redirect('posts:index', movie_pk)
    else:
        post_form = PostForm()
        
    context = {
        'movie_pk': movie_pk,
        'post_form': post_form,
    }
    return render(request, 'posts/create.html', context)
    
@login_required
def delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    movie_pk = post.movie_id
    if request.method == 'POST':
        post.delete()
    return redirect('posts:index', movie_pk)
    
@login_required
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)
    
@login_required
def update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post = post_form.save()
            return redirect('posts:detail', post.pk)
    else:
        post_form = PostForm(instance=post)
    context = {
        'post_form': post_form,
        'post': post,
    }
    return render(request, 'posts/update.html', context)
    
@login_required
def comment_create(request, post_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_pk
        comment.save()
    return redirect('posts:detail', post_pk)
    # else:
    #     return redirect('posts:detail', post_pk)
  
@login_required
def comment_delete(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user:
        return redirect('posts:detail', post_pk)
    comment.delete()
    return redirect('posts:detail', post_pk)

posts/templates/posts/_board.html
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>대시보드 템플릿</title>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
* { font-family: NanumGothic, 'Malgun Gothic'; }
body { padding-top: 50px; }
.sub-header {
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}
.navbar-fixed-top { border: 0; }
.sidebar { display: none; }
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    left: 0;
    z-index: 1000;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto;
    background-color: #f5f5f5;
    border-right: 1px solid #eee;
  }
}
.nav-sidebar {
  margin-right: -21px;
  margin-bottom: 20px;
  margin-left: -20px;
}
.nav-sidebar > li > a {
  padding-right: 20px;
  padding-left: 20px;
}
.nav-sidebar > .active > a,
.nav-sidebar > .active > a:hover,
.nav-sidebar > .active > a:focus {
  color: #fff;
  background-color: #428bca;
}
.main { padding: 20px; }
@media (min-width: 768px) {
  .main {
    padding-right: 40px;
    padding-left: 40px;
  }
}
.main .page-header { margin-top: 0; }
.placeholders {
  margin-bottom: 30px;
  text-align: center;
}
.placeholders h4 { margin-bottom: 0; }
.placeholder { margin-bottom: 20px; }
.placeholder img {
  display: inline-block;
  border-radius: 50%;
}

th, td {
    color:white;
}
</style>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js"></script>
<script src="//getbootstrap.com/assets/js/docs.min.js"></script>
</head>
<body>


      <h2 class="sub-header text-white">토론하기!</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <!--<tr class="d-flex justify-content-between">-->
            <tr class="d-flex justify-content-between">
              <div>
                <th>제목</th>
              </div>
              <!--<th>컬럼1</th>-->
              <!--<th>컬럼2</th>-->
              <div class="">
                <th>댓글</th>
                <th>마지막 댓글</th>
              </div>
            </tr>
          </thead>
          <tbody>
            {% for post in posts %}
            <tr>
              
                <td>{{ post.title }}</td>
              
              <!--<td>Lorem</td>-->
              <!--<td>ipsum</td>-->
              
                <td>dolor</td>
                <td>dolor</td>
              
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</body>
</html>

posts/templates/posts/create.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-outline-primary">Cancel</button>
            <a href="{% url 'posts:index' movie_pk %}" class="btn btn-info">Back</a>
        {% endbuttons %}
    </form>
</body>
</html>

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block head %}
    <style>
        /*p {*/
        /*    color: white;*/
        /*}*/
        .container {
            color: white;
            /*background-image: url("{{ movie.poster_url }}");*/
            
        }
        
        hr{ 
            height: 1px;
            color: white;
            background-color: white;
            border: none;
        }
        
    </style>
{% endblock %}
{% block content %}
<div class="container">
    <br>
    <h1>{{ post.title }}</h1>
    <!--<p>{{ post.content }}</p>-->
    {% if post.spoiler %}
        <!--<p>이 코멘트에는 스포일러가 있어요. <a href="" class="text-danger font-weight-bold">보기</a></p>-->
        <input class="spoilerbutton text-danger font-weight-bold" type="button" value="스포일러가 포함된 글입니다. 확인하려면 클릭하세요." onclick="this.value=this.value=='스포일러가 포함된 글입니다. 확인하려면 클릭하세요.'?'{{ post.content }}':'스포일러가 포함된 글입니다. 확인하려면 클릭하세요.';">
        <div class="spoiler"><div>
        <!--<p>test  </p>-->
        <!--<p>  </p>-->
        </div></div>
        
        <!--<button type="button" class="btn btn-outline-light">{{ score.review }}</button>-->
        <!--<p>스포일러가 포함된 댓글입니다. 댓글을 보려면 마우스를 올려주세요.</p>-->
    {% else %}
        <p>{{ post.content }}</p>
    {% endif %}
    
    
    <form action="{% url 'posts:update' post.pk %}" style="display:inline;">
        <input type="submit" value="수정"/>
    </form>
    <form action="{% url 'posts:delete' post.pk %}" method="POST" style="display:inline;">
        {% csrf_token %}
        <input type="submit" value="삭제"/>
    </form>
    <form action="{% url 'posts:index' post.movie_id %}" style="display:inline;">
        <input type="submit" value="뒤로가기"/>
    </form>
    
    <!--<span class="custom-br"></span>-->
    <hr style="color:white;">
    {% for comment in post.comment_set.all %}
        <b>{{ comment.user }}</b>:
        {% if comment.spoiler %}
            <input class="spoilerbutton text-danger font-weight-bold" type="button" value="스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요." onclick="this.value=this.value=='스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요.'?'{{ comment.content }}':'스포일러가 포함된 댓글입니다. 확인하려면 클릭하세요.';">
            <div class="spoiler"><div>
            </div></div>
        {% else %}
            <span>{{ comment.content }}</span>
        {% endif %}
        {% if comment.user == request.user %}
            <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <input type="submit" value="삭제"/>
            </form>
        {% endif %}
        
        <span class="text-muted">{{ post.comment_set.all | length }}</span>
        <span class="text-muted">{{ comment.created|timesince }} 전</span>
        <br>
    {% endfor %}
    <hr style="color:white;">
    <!--<span class="custom-br"></span>-->
    
    {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <input type="submit" value="작성하기"/>
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}"><p>로그인이 필요합니다.</p></a>
    {% endif %}
</div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{# load bootstrap_pagination #}
{% block head %}
<style>
    .border-3 {
        border-width:3px !important;
    }
</style>

{% endblock %}

{% block content %}

    <br>
    <br>
    <br>
    
    <div class="container">
    <h1 class="text-white">{{ movie_pk }}</h1>
        <div>
            <div class="list-group border-bottom border-success border-3">
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <div class="d-flex justify-content-start">
                        <h5 class="mb-1"><b>제목</b></h5>
                        </div>
                        <div class="d-flex justify-content-end">
                            <div>
                                <span class="px-5"><b>status</b></span>
                                <span class="px-5"><b>replies</b></span>
                                <span class="pl-5 pr-1"><b>lastreply</b></span>
                            </div>
                        </div>
                    </div>
                    
                </a>
            </div>
            
            {% for post in post_list %}
            <div class="list-group">
                <a href="{% url 'posts:detail' post.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small>{{ post.created|timesince }} 전</small>
                    </div>
                    
                </a>
            </div>
            {% empty %}
            <div class="list-group">
                <div class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">게시글이 존재하지 않습니다.</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>  
        
        
        
        <div class="pagination d-flex justify-content-center">
            <span class="step-links">
                {% if post_list.has_previous %}
                    <a href="?page=1">first</a>
                    <a href="?page={{ post_list.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current text-white">
                    Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
                </span>
        
                {% if post_list.has_next %}
                    <a href="?page={{ post_list.next_page_number }}">next</a>
                    <a href="?page={{ post_list.paginator.num_pages }}">last</a>
                {% endif %}
            </span>
        </div>
        
   
    </div>
    
    

    <!-- pagination -->
    
    
    
    
   
    
{% endblock %}

posts/templates/posts/update.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EDIT</title>
</head>
<body>
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-outline-primary">Cancel</button>
        <a href="{% url 'posts:detail' post.pk %}" class="btn btn-info">Back</a>
    {% endbuttons %}
    </form>
</body>
</html>